.zbPageTitle .ptBody .pageType{
	font-family:"Verdana","Geneva",san-serif;
	font-weight:700;
	font-size:109%;
}
.zbPageTitle h1, .bPageTitle h2{
	display:none;
}

.zpageDescription{
	color:#CBD0D2;
}

.zblank{
	display:none;
}

.zptBreadcrumb{
	display:none;
}

.middleText{
	 
	font-family: Arial, Helvetica, Verdana, sans-serif;
	color: #525252;
	font-size: 18px;
	font-weight: bold;
 
}
 
.header-login-status { font-family: Arial, Helvetica, Verdana, sans-serif; text-decoration: none; font-size: 14px; color: #525252; font-weight: bold; width: 33.3%; float: right; text-align: right; padding: 5px 30px; }
 
.header-login-status : hover  { color: #636363; text-decoration: underline; }



.btn, .button, .formulaButton, .btnWhatsNew {
    
	font-family: 'Verdana','Geneva',sans-serif;
	background-image: url("/img/bgButton.gif");
	background-repeat: repeat-x;
	background-position: left top;
	border-right: 1px solid rgb(92, 93, 97);
	border-width: medium 1px 1px medium;
	border-style: none solid solid none;
	border-color: -moz-use-text-color rgb(92, 93, 97) rgb(92, 93, 97) -moz-use-text-color;
	font-size: 90%;
	color: rgb(255, 255, 255);
	padding: 1px 3px;
	cursor: pointer;
	font-weight: bold;
	display: inline;

		color: #ffffff;
		text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25)
		background: #51a351;
		background-image: -moz-linear-gradient(top, #62c462, #51a351);
		background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#62c462), to(#51a351));
		background-image: -webkit-linear-gradient(top, #62c462, #51a351);
		background-image: -o-linear-gradient(top, #62c462, #51a351)
		background-image: linear-gradient(to bottom, #62c462, #51a351)
		background-repeat: repeat-x;
	  	border-color: #51a351 #51a351 #387038;
		border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
		filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ff62c462', endColorstr='#ff51a351', GradientType=0);
	  	filter: progid:DXImageTransform.Microsoft.gradient(enabled=false);
	
	height: 18px;
	margin: 4px;

}

#tabsNewBar { clear: both; padding: 0; font-size: 12px; font-weight: bold; border-bottom: 18px solid #2b4b79}

#tabBar2 td { border: 0; padding: 0; list-style-type: none; text-align: center; height: 33px;}
#tabBar2 td { display: block; float: left; text-align: left; padding: 0; margin: 0; }
#tabBar2 td a {
line-height: 1em;
border-top: 1px solid #c4c4c4;
border-left: 1px solid #c4c4c4;
border-right: 1px solid #c4c4c4;
padding: 8px 22px;
border-bottom: none;
margin: 0 1px 0 0;
text-decoration: none;
display: block;
text-align: center;
color: #6d6d6d;
-webkit-border-top-left-radius: 5px;
-webkit-border-top-right-radius: 5px;
-moz-borderbox-radius-topleft: 5px;
-moz-borderbox-radius-topright: 5px;
border-top-left-radius: 5px;
border-top-right-radius: 5px;
background: #f3f3f3;
background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIwJSIgeTI9IjEwMCUiPgogICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iI2YzZjNmMyIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiNiNGI0YjQiIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
background: -moz-linear-gradient(top,  #f3f3f3 0%, #b4b4b4 100%);
background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#f3f3f3), color-stop(100%,#b4b4b4));
background: -webkit-linear-gradient(top,  #f3f3f3 0%,#b4b4b4 100%);
background: -o-linear-gradient(top,  #f3f3f3 0%,#b4b4b4 100%);
background: -ms-linear-gradient(top,  #f3f3f3 0%,#b4b4b4 100%);
background: linear-gradient(to bottom,  #f3f3f3 0%,#b4b4b4 100%);
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f3f3f3', endColorstr='#b4b4b4',GradientType=0 );
}



#tabBar td a:hover { 
background: #f8f8f8; 
background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIwJSIgeTI9IjEwMCUiPgogICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzNlNmViMiIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiMyZTUwODIiIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
background: -moz-linear-gradient(top,  #f3f3f3 0%, #f8f8f8 100%);
background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#f3f3f3), color-stop(100%,#f8f8f8));
background: -webkit-linear-gradient(top,  #f3f3f3 0%,#f8f8f8 100%);
background: -o-linear-gradient(top,  #f3f3f3 0%,#f8f8f8 100%);
background: -ms-linear-gradient(top,  #f3f3f3 0%,#f8f8f8 100%);
background: linear-gradient(to bottom,  #f3f3f3 0%,#f8f8f8 100%);
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f3f3f3', endColorstr='#f8f8f8',GradientType=0 );
}




#tabBar td.currentTab a { 

color: #FFFFFF;  
background: #2b4b79;
background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIwJSIgeTI9IjEwMCUiPgogICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzNlNmViMiIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiMyZTUwODIiIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
background: -moz-linear-gradient(top,  #2b4b79 0%, #2e5082 100%);
background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#2b4b79), color-stop(100%,#2e5082));
background: -webkit-linear-gradient(top,  #2b4b79 0%,#2e5082 100%);
background: -o-linear-gradient(top,  #2b4b79 0%,#2e5082 100%);
background: -ms-linear-gradient(top,  #2b4b79 0%,#2e5082 100%);
background: linear-gradient(to bottom,  #2b4b79 0%,#2e5082 100%);
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#2b4b79', endColorstr='#2e5082',GradientType=0 );
}
 
 

.tabNavigation {
	background-image: url(/s.gif);
	background-color: #FFFFFF;
	margin:0px;
	padding: 0px;
}
 


.tab td {
	background-image: url(/s.gif);
	border-bottom-color: #FFFFFF;
	margin:0px;
	padding: 0px;

}



.tab td div,
.tab .last div {
	background-image: url(/s.gif);
	padding-right:0px;
	padding-left:0px;
}



.tab .currentTab {
	background-image: url(/s.gif);
	background-color: #FFFFFF; 
	border-right-color: #FFFFFF;
	color: #FFFFFF; 
}



.tab .currentTab div {  
	color: #FFFFFF; 
	 
	background-image: url(/s.gif);
	padding-right:0px;
	padding-left:0px;
}

 

